# Generated by Django 3.1.4 on 2021-01-26 13:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('patronymic', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=16, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('taxpayer_id', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_taxpayer_id', message='ИНН - последовательность из 12 цифр', regex='\\d{12}')])),
            ],
        ),
        migrations.CreateModel(
            name='LegalContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.contact')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='LegalAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.address')),
            ],
        ),
    ]
