# Generated by Django 3.1.4 on 2021-01-26 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_work_in_progress', models.BooleanField(default=True)),
                ('DTU_num', models.PositiveSmallIntegerField(default=0)),
                ('DTL_num', models.PositiveSmallIntegerField(default=0)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('number', models.PositiveSmallIntegerField()),
                ('begin', models.DateField()),
                ('end', models.DateField()),
                ('total', models.PositiveBigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dosimetria.client')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dosimetria.quarter')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('total', models.PositiveIntegerField()),
                ('is_returned', models.BooleanField(default=False)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dosimetria.client')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_at', to='dosimetria.quarter')),
                ('returned_at', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returned_at', to='dosimetria.quarter')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('is_returned', models.BooleanField(default=False)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dosimetria.client')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dosimetria.quarter')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('begin', models.DateField()),
                ('end', models.DateField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dosimetria.client')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.address')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dosimetria.client')),
            ],
        ),
    ]
